title: "Space Exploration Society"
logo:
  path: assets/img/ses.jpg
  height: 100
email: ses@iitbhilai.ac.in
collections:
  pages:
    output: true
    permalink: /:title/

description: >-
  Official site of the Space Exploration Society ,IIT Bhilai. 
  Explore our projects, missions, and activities!
baseurl: "/SES"
url: "https://ses-iitbh.github.io"
include:
  - _pages
