title: "Space Exploration Society"
logo:
  path: assets/img/ses.jpg
  height: 100
email: ashishdash2410@gmail.com
collections:
  pages:
    output: true
    permalink: /:title/

description: >-
  Official site of the Space Exploration Society ,IIT Bhilai. 
  Explore our projects, missions, and activities!
baseurl: "/SES-Website" 
url: "https://ashish-kumar-dash.github.io"
include:
  - _pages


